import { createSlice } from "@reduxjs/toolkit";
// createSlice is a function from Redux Toolkit that helps us create
// a slice of the Redux state,
// which includes the state and the reducers to change the state.

const counterSlice = createSlice({
  name: "counter", //name of the slice
  initialState: {
    count: 0,
  },
  //   reducers: An object containing functions (reducers)
  //     that define how the state can be changed.
  //      Here, we have two reducers:
  reducers: {
    increment: (state) => {
      state.count++;
    },
    decrement: (state) => {
      state.count--;
    },
  },
});
// A slice typically consists of the state and the reducers that change that state.

export const { increment, decrement } = counterSlice.actions;
// This line exports the action creators generated by createSlice.
// These action creators are functions that will be used to dispatch actions to the store.
export default counterSlice.reducer;
// This line exports the reducer function generated by createSlice.
// This reducer will be used to configure the Redux store.
